ProyectoDEP-master/ProyectoDEP/urls.py
from os import name
from django import urls
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, logout_then_login
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.urls.conf import re_path
from django.views.static import serve

from aplicacionAdministrador.views import administrar_usuarios, detalle_solicitud, detalle_solicitud_cancelacion, eliminar_solicitud_recursos_financieros, guardar_dictaminado, seleccion_usuarios, ver_administrador, ver_solicitudes_cambio, ver_solicitudes_cancelacion, ver_solicitudes_comite, registrar_administrador, eliminar_administrador, editar_administrador, inicio, ver_solicitudes_equivalencia, ver_solicitudes_movilidad, ver_solicitudes_recursos_financieros, ver_solicitudes_traslado

from aplicacionAlumnos.views import detalle_solicitud_alumno, inicio_alumno, alumno_equivalencia, mostrar_template_archivo, muestra_archivos_cambio, muestra_archivos_equivalencia, muestra_archivos_movilidad, muestra_archivos_peticion, muestra_archivos_traslado,  pdf_equivalencia, pdf, pdf_cambio, pdf_traslado, prueba_correo, registrar_alumno, solicitar_referencia, solicitud_cambio, solicitud_comite, pdf_comite, solicitud_traslado, ver_mis_solicitudes, detalle_alumno, cambiar_psw, recuperar_psw

urlpatterns = [

    # -------------------------- LOGIN / LOGOUT --------------------------  #
    path('adminn/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('accounts/login/',LoginView.as_view(template_name="html/login_administrador.html"), name="login"),
    path('logout/', logout_then_login, name='logout'),


    # -------------------------- ADMINSTRADORES --------------------------  #
    path('inicio_administrador/',login_required(ver_administrador), name='administrador'),
    path('administrador_usuarios/', login_required(administrar_usuarios), name='usuarios'),
    path('seleccion_usuarios/', seleccion_usuarios, name='seleccion_usuarios'),
    path('registrar_administrador/', login_required(registrar_administrador), name='registrar_administrador'),
    path('eliminar_administrador/<int:id_administrador>', login_required(eliminar_administrador), name="eliminar_administrador"),
    path('editar_administrador/<int:id_administrador>', login_required(editar_administrador), name="editar_administrador"),


    # ------------- SOLICITUDES -------------  #
    path('solicitudes_cambio/', login_required(ver_solicitudes_cambio), name='cambio'),
    path('solicitudes_comite/', login_required(ver_solicitudes_comite), name='comite'),
    path('solicitudes_cancelacion/', login_required(ver_solicitudes_cancelacion), name='cancelacion'),
    path('solicitud_movilidad/', login_required(ver_solicitudes_movilidad), name='movilidad'),
    path('solicitud_traslado/', login_required(ver_solicitudes_traslado), name='traslado'),
    path('solicitud_equivalencia/',login_required(ver_solicitudes_equivalencia), name='equivalencia'),
    path('solicitud_recursos_financieros/',login_required(ver_solicitudes_recursos_financieros), name='recursos_financieros'),
    path('eliminar_solicitud_recursos_financieros/<int:id_peticion>',login_required(eliminar_solicitud_recursos_financieros), name="eliminacion_solicitud_recursos_financieros"),
    path('detalle_solicitud/<int:id_solicitud>', login_required(detalle_solicitud), name="detalle_solicitud"),
    path('detalle_solicitud_cancelacion/<int:id_solicitud>', login_required(detalle_solicitud_cancelacion), name="detalle_solicitud_cancelacion"),

    path('mis_solicitudes/', ver_mis_solicitudes, name='ver_mis_solicitudes'),

    path('dictaminado/', guardar_dictaminado, name='guarda'),

    # -------------------------- ALUMNOS --------------------------  #
    path('login_alumno/',LoginView.as_view(template_name="login_alumno.html"), name="login_alumno"),
    path('inicio_alumno/', login_required(inicio_alumno), name='alumno'),
    path('registrar_alumno/', registrar_alumno, name="registrar_alumno"),
    path('detalle_solicitud_alumno/<int:id_alumno>',login_required(detalle_solicitud_alumno), name="detalle_solicitud_alumno"),
    path('detalle_alumno/<int:numero_control>', login_required(detalle_alumno), name='detalle_alumno'),
    path('cambiar_psw/<int:numero_control>', login_required(cambiar_psw), name='cambiar_psw'),
    path('recupera_psw/', recuperar_psw, name='recuperar_psw'),
    path('solicitar_referencia/<int:numero_control>', login_required(solicitar_referencia), name='solicitar_referencia'),
    


    # ------------- PDFS -------------  #
    path('alumno_equivalencia/', alumno_equivalencia, name="alumno_equivalencia"),
    path('pdf_equivalencia/', pdf_equivalencia, name="pdf_equivalencia"),
    path('pdf/', pdf, name="pdf"),
    path('pdfequivalencia/', login_required(pdf_equivalencia), name="pdf_equivalencia"),
    path('pdf_cambio', pdf_cambio, name = 'pdf_cambio' ),
    path('pdf_comite', pdf_comite, name='pdf_comite'),
    path('pdf_traslado', pdf_traslado, name = 'pdf_traslado'),


    # ------------- DRAG AND DROPS DE ARCHIVOS -------------  #
    path('archivos_cambio_carrera/', muestra_archivos_cambio, name='archivosCambio'),
    path('archivos_peticion/', muestra_archivos_peticion, name='archivosPeticion'),
    path('archivos_movilidad/', muestra_archivos_movilidad, name='archivosMovilidad'), 
    path('archivos_traslado/', muestra_archivos_traslado, name='archivosTraslado'), 
    path('archivos_equivalencia/', muestra_archivos_equivalencia, name='archivosEquivalencia'), 
    path('prueba_archivo/', mostrar_template_archivo, name='prueba'),

    path('prueba_correo', prueba_correo, name='pruebaCorreo'),
    # path('contacto/', correo, name='contact'),
]


urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

# if settings.DEBUG:
#     urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 
    # path('solicitudes_participacion/', login_required(ver_solicitudes_participacion), name='participacion'),
    # path('solicitudes_convalidacion/', login_required(ver_solicitudes_convalidacion), name='convalidacion'),
    # path('solicitudes_resolucion/', login_required(ver_solicitudes_resolucion), name='resolucion'),

    # path('detalle_administrdaor/<int:id_administrador>', detalle_administrador, name="detalle_administrador"),
    #path('eliminar_administrador/<int:id_administrador>', eliminar_administrador, name="eliminar_administrador"),
    #path('editar_administrador/<int:id_administrador>', editar_administrador, name="editar_administrador"),

ProyectoDEP-master/aplicacionAlumnos/models.py
from django.db import models

# Create your models here.
# modelos del alumno

ProyectoDEP-master/aplicacionDB/models.py
from datetime import date
import os
from django.db import models


# Create your models here.
class Estudiante(models.Model):
    numeroControl = models.CharField(max_length=10)
    nombres = models.CharField(max_length=255)
    apellidoPaterno = models.CharField(max_length=255)
    apellidoMaterno = models.CharField(max_length=255)
    carrera = models.CharField(max_length=255)
    correo = models.CharField(max_length=255)
    contraseña = models.CharField(max_length=20)

    def __str__(self):
        return f'Estudiantes: {self.numeroControl} {self.nombres} {self.apellidoPaterno} {self.apellidoMaterno} {self.carrera} {self.contraseña}'


class Administrador(models.Model):
    nombreUsuario = models.CharField(max_length=255)
    contraseña = models.CharField(max_length=20)
    correo = models.CharField(max_length=255)
    nombres = models.CharField(max_length=255)
    apellidoMaterno = models.CharField(max_length=255)
    apellidoPaterno = models.CharField(max_length=255)
    telefono = models.CharField(max_length=255)
    departamento = models.CharField(max_length=255)
    rangoAdministrador = models.CharField(max_length=255)

    def __str__(self):
        return f'Administradores: {self.idAdmin} {self.nombreUsuario} {self.contraseña} {self.rangoAdministrador}'

class Tramites(models.Model):
    descripcion = models.CharField(max_length=255)

    def __str__(self):
        return self.descripcion

class Solicitudes(models.Model):
    numeroControl = models.ForeignKey(Estudiante, on_delete=models.SET_NULL, null=True)
    numeroFolio = models.CharField(max_length=255)
    estatusAlumno = models.CharField(max_length=255)
    estatusAdministrador = models.CharField(max_length=255)
    comentarios = models.CharField(max_length=255, null=True)
    fechaCreacion = models.DateField()
    fechaCierre = models.DateField(null=True)
    tipoTramite = models.ForeignKey(Tramites, on_delete=models.SET_NULL, null=True)
    dictamen = models.FileField(blank=True, upload_to='dictaminados', max_length=255)

    def __str__(self):
        return f'Solicitudes: {self.numeroControl} {self.numeroFolio} {self.estatusAlumno} {self.estatusAdministrador}'

    def nombre_dictaminado(self):
        return os.path.basename(self.dictamen.name)

class Archivos (models.Model):
    documento = models.FileField(blank=True, upload_to='documentos', max_length=255)
    numeroFolio = models.ForeignKey(Solicitudes, on_delete=models.SET_NULL, null=True)

    def filename(self):
        return os.path.basename(self.documento.name)

class Documentos(models.Model):
    numeroFolio = models.ForeignKey(Solicitudes, on_delete=models.SET_NULL, null=True)
    numeroControl = models.ForeignKey(Estudiante, on_delete=models.SET_NULL, null=True)
    archivos = models.FileField(blank=True, upload_to='documentos', max_length=255)

    def __str__(self):
        return f'Documentos: {self.id} {self.numeroFolio} {self.archivo}'

class Referencia(models.Model):
    numeroControl = models.CharField(max_length=255)
    nombres =  models.CharField(max_length=255)
    tipoTramite = models.CharField(max_length=255)
    correo =  models.CharField(max_length=255)
    carrera = models.CharField(max_length=255)

    def __str__(self):
        return f'Referencias: {self.numeroControl} {self.nombres} {self.carrera} {self.tipoTramite} {self.correo} {self.carrera}'

ProyectoDEP-master/aplicacionAlumnos/forms.py
from typing import Text
from django import forms
# from django.db.models.fields import CharField

from django.forms import TextInput
from django.forms import widgets
from django.forms.widgets import EmailInput, FileInput, NumberInput, PasswordInput

from aplicacionDB.models import Documentos, Estudiante

# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User

class AlumnoForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = '__all__'
        MIS_CHOICES = (('ISC', 'ISC'), ('ITICS', 'ITICS'), ('ELECTRICA', 'ELECTRICA'), ('INSDUSTRIAL', 'INDUSTRIAL'),)
        widgets = {
            'numeroControl':TextInput(attrs={'class':'form__field'}),
            'nombres':TextInput(attrs={'class':'form__field'}),
            'apellidoPaterno':TextInput(attrs={'class':'form__field'}),
            'apellidoMaterno':TextInput(attrs={'class':'form__field'}),
            'carrera':forms.Select(choices=MIS_CHOICES, attrs={'class':'form__field'}),
            'correo': EmailInput(attrs={'class':'form__field'}),
            'contraseña': PasswordInput(attrs={'class':'form__field'})
        }

class DocumentoForm(forms.ModelForm):
    class Meta:
        model = Documentos
        fields = '__all__'
        # exclude = ('',)
        # MIS_CHOICES = (('1', 'SuperAdministrador'), ('2', 'Administrador'),)
        widgets = {
            'numeroFolio': TextInput(attrs={'class': 'form-control'}),
            'numeroControl': TextInput(attrs={'class': 'form-control'}),
            'archivos': FileInput(attrs={})

        }

# class User

ProyectoDEP-master/aplicacionAlumnos/templates/cambio_archivos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {% block title %} {% endblock %} </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/solicitudes.css'%}">
        <link rel="stylesheet" href="{% static 'css/inicio_administracion.css'%}">
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Round" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'CSS/drag_drop.css' %}">
        <script src="https://kit.fontawesome.com/b5d7e81e44.js" crossorigin="anonymous"></script>
    </head>


    <body>

       
        <div class="">
            <h2>Arrastra y suelta los archivos</h2>
            <form action="." method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="drop-area">
                    <span>O</span>
                    <button>Selecciona tus archivos</button>
                    <input type="file" name="archivos" id="input-file" multiple hidden>
                </div>
                <input type="text" name="numeroFolio" id="folio" class="form-control" placeholder="Ingresa el número de folio">

                <input type="submit" class="btn btn-success">
                <div id="preview"></div>
            </form>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    </body>

</html>

ProyectoDEP-master/aplicacionAlumnos/templates/inicio_alumno.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {% block title %} {% endblock %} </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/solicitudes.css'%}">
        <link rel="stylesheet" href="{% static 'css/inicio_administracion.css'%}">
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Round" rel="stylesheet">
        <script src="https://kit.fontawesome.com/b5d7e81e44.js" crossorigin="anonymous"></script>
        </he ad>

        {% if user.groups.all.0.name == 'Alumno' %}

        <body>
            {%include 'menu_alumnos.html'%}
            <div id="main">
                <div class="container">
                </div>
                <div class="container" style="width: 75%;">
                    <h1 class="frase" style="font-size: 2rem;font-weight: 100;">¡Bienvenido al Sistema de Tramites Escolar!<br> Seleccione una opcion del menú para interactuar con el sistema</h1>

                </div>
            </div>


            <div class="todo">
                {% block content %} {% endblock %}
            </div>



            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

        </body>
        {%else%}
        <style>
            body {
                background-color: #2b2d42;
                align-items: center;
            }
        </style>
        <div class="modal-dialog modal-dialog-centered" style="margin-top: 10%;">
            <div class="modal-content" style="background-color: #e9ecef;">
                <div class="modal-header">
                    <div class="row">
                        <h5 class="modal-title" id="staticBackdropLabel">
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="circle-exclamation" class="svg-inline--fa fa-circle-exclamation" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" height="1.5rem" width="1.5rem">
                        <path fill="currentColor" d="M256 0C114.6 0 0 114.6 0 256s114.6 256 256 256s256-114.6 256-256S397.4 0 256 0zM232 152C232 138.8 242.8 128 256 128s24 10.75 24 24v128c0 13.25-10.75 24-24 24S232 293.3 232 280V152zM256 400c-17.36 0-31.44-14.08-31.44-31.44c0-17.36 14.07-31.44 31.44-31.44s31.44 14.08 31.44 31.44C287.4 385.9 273.4 400 256 400z">
                        </path>
                    </svg> ¡Atención!</h5>
                    </div>

                </div>
                <div class="modal-body">
                    <div class="row">
                        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="circle-exclamation" class="svg-inline--fa fa-circle-exclamation" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" height="4rem" width="4rem" color="#ba181b">
                        <path fill="currentColor" d="M256 0C114.6 0 0 114.6 0 256s114.6 256 256 256s256-114.6 256-256S397.4 0 256 0zM232 152C232 138.8 242.8 128 256 128s24 10.75 24 24v128c0 13.25-10.75 24-24 24S232 293.3 232 280V152zM256 400c-17.36 0-31.44-14.08-31.44-31.44c0-17.36 14.07-31.44 31.44-31.44s31.44 14.08 31.44 31.44C287.4 385.9 273.4 400 256 400z">
                        </path>
                    </svg>
                    </div>
                    <br>
                    <h6 style="text-align: center;">No tiene autorización para visualizar este contenido</h6>
                    <a href="{% url 'logout' %}" style="width: 50%; margin: 2rem 25% 3rem 25%; border-radius: 15px;" class="btn btn-warning"> Salir</a>
                </div>
            </div>
        </div>
        {% endif %}

</html>

ProyectoDEP-master/aplicacionAlumnos/templates/login_alumno.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>LOGIN</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/inicio_administracion.css'%}">
        <script src="https://kit.fontawesome.com/b5d7e81e44.js" crossorigin="anonymous"></script>
    </head>

    <body >
        <div class="containerLogin">
            <div class="row">
                <div class="col">
                    <img src="{% static 'images/logo2.png'%}" style="width:80%; height: 75%; margin:12% 10% 12% 10% ;" alt="">
                </div>

                <div class="col">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="text-center">
                            <i class="fas fa-user-circle fa-5x"></i>
                        </div>
                        <h3>INICIAR SESION</h3>
                            <label for="nombreUsuario">Nombre de Usuario:</label>
                            <input type="text" class="form-control"  placeholder="Ingrese su nombre de usuario" name="username">


                            <label for="contraseñaUsuario">Contraseña:</label>
                            <input type="password" class="form-control"  placeholder="Ingrese su contraseña" name="password">

                        <button type="submit" class="btn btn-primary">INGRESAR</button>

                        <h3>¿No estas registrado en el sistema?</h3>
                        <a href="{%url 'registrar_alumno'%}">Registrate aqui</a>
                    </form>
                </div>
            </div>
        </div>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    </body>
</html>

ProyectoDEP-master/aplicacionAlumnos/templates/modal_cambio.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">Formato para la Convalidacion de Estudios</h2>
            <button class="close" type="button" data-dismiss = "modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">

        </div>
        <div class="modal-footer">
            <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
            <button class="btn btn-primary" type="submit">Confirmar</button>
        </div>
    </div>

</div>

ProyectoDEP-master/aplicacionAlumnos/templates/registrar_alumno.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {% block title %} {% endblock %} </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/solicitudes.css'%}">
        <link rel="stylesheet" href="{% static 'css/inicio_administracion.css'%}">
        <link rel="stylesheet" href="{%static 'css/inputs.css'%}">
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Round" rel="stylesheet">
        <script src="https://kit.fontawesome.com/b5d7e81e44.js" crossorigin="anonymous"></script>
    </head>

    <body style="background-color: #2b2d42;">

        <div class="modal-dialog modal-lg">
            <div class="modal-content" style="background-color: #f8f8f8;">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Registrar Alumno</h5>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <form method="POST" action=".">
                            <div class="row">
                                <div class="col">
                                    <div class="form__group" style="width: 100%;">
                                        <label for="nombreAdministrador">Nombre o Nombres:</label> {{formaAlumno.nombres}}
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form__group" style="width: 100%;">
                                        <label for="primerApellido">Primer Apellido</label> {{formaAlumno.apellidoPaterno}}
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form__group" style="width: 100%;">
                                        <label for="segundoApellido">Segundo Apellido</label> {{formaAlumno.apellidoMaterno}}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form__group" style="width: 100%;">
                                        <label for="carrera">Carrera</label> {{formaAlumno.carrera}}
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form__group" style="width: 100%;">
                                        <label for="nombreUsuario">Número de Control</label> {{formaAlumno.numeroControl}}
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col">
                                    <div class="form__group" style="width: 100%;">
                                        <label for="correoAdministrador">Correo Institucional</label>
                                    </div>
                                    <div class="row">
                                        <label for="correo"><input type="text" name="correo" id="correo" class="form__field" style="width: 50%;" maxlength="9">@morelia.tecnm.mx</label>
                                    </div>
                                    <div style="display: none; background-color: aqua;">
                                        {{formaAlumno.correo}}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form__group" style="width: 100%;">
                                        <label for="contraseña">Contraseña</label> {{formaAlumno.contraseña}}
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <button type="submit" class="btn btn-warning" style="width: 50%; margin: 2rem 25% 1rem 25%; border-radius: 30px;">Registrarse</button> {% csrf_token %}
                                <a href="{% url 'logout' %}" class="btn btn-danger" style="width: 50%; margin: 0rem 25% 0rem 25%; border-radius: 30px;"> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>




        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
        <script>
            $(document).ready(function() {
                $("#correo").keyup(function() {
                    var value = $(this).val();
                    $("#id_correo").val(value + "@morelia.tecnm.mx");
                });
            });
        </script>

    </body>

</html>

ProyectoDEP-master/aplicacionAlumnos/templates/temporal.html
estudiante = get_object_or_404(Estudiante, pk=id_alumno)
      if request.method == 'POST':
            formaAlumno = AlumnoForm(request.POST, instance=estudiante)
            user = User.objects.get(username=estudiante.numeroControl)
            user.set_password('psw')
            user.save()
            formaAlumno.save()
      else:
            formaAlumno = AlumnoForm(instance=estudiante)

      return render(request, 'editar_alumno.html', {'formaAlumno':formaAlumno, 'admin':estudiante})